baseURL = 'https://gajdosik.org/'
languageCode = 'en-us'
title = 'Andreas Gajdosik'
theme = 'fineartsy'
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

[params]
  [params.sectionSingularNames]
    artworks = "artwork"
    exhibitions = "exhibition"
    mentions = "mention"
    thoughts = "thought"
    texts = "text"
